name: Go test annotations
description: Add annotations from `go test` to your GitHub Actions workflow runs

author: Michael Cousins

inputs:
  test-results:
    description: Path to the test results file from `go test -json`
    default: 'test.json'

runs:
  using: node20
  main: action.js
